version: '3.9'

services:
  manage-saving:
    container_name: manage-saving
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - 5000:${PORT}
    stdin_open: true
    tty: true
    volumes:
      - .:/app
  mysqldb:
    container_name: mysql-managing-saving
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
