name: Docker Image CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo PORT=${{secrets.PORT}} > .env
          echo KEY_HASH=${{secrets.KEY_HASH}}>> .env
          echo DB_HOST=${{secrets.DB_HOST}}>> .env
          echo DB_PORT=${{secrets.DB_PORT}}>> .env
          echo DB_HOST=${{secrets.DB_HOST}}>> .env
          echo DB_USER=${{secrets.DB_USER}}>> .env
          echo DB_PASS=${{secrets.DB_PASS}}>> .env
          echo DB_NAME=${{secrets.DB_NAME}}>> .env
          echo SESSION_SECRET=${{secrets.SESSION_SECRET}}>> .env
          echo MAIL_USER=${{secrets.MAIL_USER}}>> .env
          echo MAIL_PASS=${{secrets.MAIL_PASS}}>> .env
      - name: Stop containers
        if: always()
        run: docker-compose down
      - name: Build images
        run: docker-compose build
      - name: Run containers
        run: docker-compose up -d

